# Generated by Django 5.0.6 on 2024-06-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.AlterField(
            model_name='fine',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
